services:
 
  #Servicio 1: levantar MySQL
  mysql:
    image: mysql:8.4
    container_name: mysql-microservicios
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: db_estado
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-u","root", "-prootpass"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - microservicios-net
 
  #Servicio 2: Eureka
  eureka-server:
    build:
      context: ./eurekaserver
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    restart: on-failure
    networks:
      - microservicios-net
 
  #Servicio 3: estado
  gestion_estado:
    build:
      context: ./gestion_estado
      dockerfile: Dockerfile
    container_name: gestion_estado
    volumes:
      - ./logs/gestion_estado:/app/logs
    ports:
      - "8072:8072"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    restart: on-failure
    networks:
      microservicios-net:
        aliases:
          - gestion-estado
 
  #Servicio 4: configuracion
  gestion_configuracion:
    build:
      context: ./gestion_configuracion
      dockerfile: Dockerfile
    container_name: gestion_configuracion
    volumes:
      - ./logs/gestion_configuracion:/app/logs
    ports:
      - "8073:8073"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    restart: on-failure
    networks:
      microservicios-net:
        aliases:
          - gestion-configuracion
 
  #Servicio 5: usuarios
  gestion_usuarios:
    build:
      context: ./gestion_usuarios
      dockerfile: Dockerfile
    container_name: gestion_usuarios
    volumes:
      - ./logs/gestion_usuarios:/app/logs
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    restart: on-failure
    networks:
      microservicios-net:
        aliases:
          - gestion-usuarios
 
  #Servicio 6: direccion
  gestion_direccion:
    build:
      context: ./gestion_direccion
      dockerfile: Dockerfile
    container_name: gestion_direccion
    volumes:
      - ./logs/gestion_direccion:/app/logs
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    restart: on-failure
    networks:
      microservicios-net:
        aliases:
          - gestion-direccion
 
  #Servicio 7: inventario
  inventario:
    build:
      context: ./inventario
      dockerfile: Dockerfile
    container_name: inventario
    volumes:
      - ./logs/inventario:/app/logs
    ports:
      - "8090:8090"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    restart: on-failure
    networks:
      - microservicios-net
 
  #Servicio 8: productos
  productos-microservicio-main:
    build:
      context: ./productos-microservicio-main
      dockerfile: Dockerfile
    container_name: productos-microservicio
    volumes:
      - ./logs/productos:/app/logs
    ports:
      - "8091:8091"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    restart: on-failure
    networks:
      - microservicios-net
 
  #Servicio 9: envios
  gestion_envio:
    build:
      context: ./gestion_envio
      dockerfile: Dockerfile
    container_name: gestion_envio
    volumes:
      - ./logs/gestion_envio:/app/logs
    ports:
      - "8082:8082"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    restart: on-failure
    networks:
      microservicios-net:
        aliases:
          - gestion-envio
 
  #Servicio 10: ventas
  venta:
    build:
      context: ./venta
      dockerfile: Dockerfile
    container_name: venta
    volumes:
      - ./logs/venta:/app/logs
    ports:
      - "8092:8092"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    restart: on-failure
    networks:
      - microservicios-net
 
  #Servicio 11: api-gateway (siempre al final, depende de todos)
  api-gateway:
    build:
      context: ./apigateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8800:8800"
    depends_on:
      eureka-server:
        condition: service_started
      gestion_estado:
        condition: service_started
      gestion_configuracion:
        condition: service_started
      gestion_usuarios:
        condition: service_started
      gestion_direccion:
        condition: service_started
      inventario:
        condition: service_started
      productos-microservicio-main:
        condition: service_started
      gestion_envio:
        condition: service_started
      venta:
        condition: service_started
    restart: on-failure
    networks:
      - microservicios-net
 
volumes:
  mysql-data:
 
networks:
  microservicios-net:
    driver: bridge