spring.application.name=inventario
server.port=8090
spring.datasource.url=jdbc:mysql://localhost:3306/db_inventario?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


logging.level.com.ejemplo.msproductos=DEBUG
logging.level.org.springframework=WARN
logging.level.org.hibernate.orm.jdbc.bind=DEBUG
logging.level.root=WARN
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%5level] %logger{30} - %msg%n

springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

ms.productos.url=http://localhost:8091

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=ms-clientes
eureka.instance.instance-id=ms-clientes:${server.port}

