spring.application.name=eurekaserver

server.port=8761

#evita que eureka se registre a si mismo
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

#Url de acceso para verificar los microservicios registrados
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.hostname=eureka-server

#Manejo de logs para eureka
logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO