server:
  port: 8071

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ruta-gestion_estados
              uri: lb://gestion_estados
              predicates:
              - Path=/api/estados,/api/estados/**
            - id: ruta-gestion_usuarios
              uri: lb://gestion_usuarios
              predicates:
                - Path=/api/usuarios,/api/usuarios/**
            - id: ruta-gestion_direccion
              uri: lb://gestion_direccion
              predicates:
                - Path=/api/direccion,/api/direccion/**
            - id: ruta-gestion_envio
              uri: lb://gestion_envio
              predicates:
                - Path=/api/envio,/api/envio/**
            - id: ruta-gestion_configuracion
              uri: lb://gestion_configuracion
              predicates:
                - Path=/api/configuracion,/api/configuracion/**
            - id: ruta-inventario
              uri: lb://inventario
              predicates:
                - Path=/api/inventario,/api/inventario/**

eureka:
  client: 
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: api-gateway
    instance-id: api-gateway:${server.port}

logging:
  level:
    '[org.springframework.cloud.gateway]': DEBUG