spring.application.name=gestionestado

server.port=8071

spring.datasource.url=jdbc:mysql://localhost:3306/bd_estado
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.com.joyeria.ms_estado_demo=DEBUG
logging.level.org.springframework=WARN
logging.level.org.hibernate.orm.jdbc.bind=DEBUG
logging.level.root=WARN

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%5level] %logger{30} - %msg%n

ms.envio.url=http://localhost:8082